"use client";

import { useEffect, useState } from "react";

export default function CodeBlockEnhancer() {
  useEffect(() => {
    // Find all code blocks generated by rehype-pretty-code
    const codeBlocks = document.querySelectorAll("[data-rehype-pretty-code-figure]");

    codeBlocks.forEach((figure) => {
      // Skip if already enhanced
      if (figure.querySelector(".code-copy-btn")) return;

      // Make figure a group for hover
      figure.classList.add("group");

      // Get the code content
      const codeElement = figure.querySelector("code");
      if (!codeElement) return;

      // Create copy button
      const button = document.createElement("button");
      button.className =
        "code-copy-btn absolute top-3 right-3 p-2 rounded border border-[var(--border-light)] bg-[var(--bg-tertiary)] text-[var(--text-muted)] hover:text-[var(--text-inverse)] hover:bg-[var(--accent)] hover:border-[var(--accent)] transition-all opacity-0 group-hover:opacity-100 z-10";
      button.setAttribute("aria-label", "Copier le code");
      button.setAttribute("title", "Copier le code");

      // Copy icon
      button.innerHTML = `
        <svg class="copy-icon" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <rect x="9" y="9" width="13" height="13" rx="2" ry="2" />
          <path d="M5 15H4a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2h9a2 2 0 0 1 2 2v1" />
        </svg>
        <svg class="check-icon hidden" width="14" height="14" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2">
          <polyline points="20 6 9 17 4 12" />
        </svg>
      `;

      button.addEventListener("click", async () => {
        const text = codeElement.textContent || "";
        try {
          await navigator.clipboard.writeText(text);
          // Show check icon
          const copyIcon = button.querySelector(".copy-icon");
          const checkIcon = button.querySelector(".check-icon");
          if (copyIcon && checkIcon) {
            copyIcon.classList.add("hidden");
            checkIcon.classList.remove("hidden");
            setTimeout(() => {
              copyIcon.classList.remove("hidden");
              checkIcon.classList.add("hidden");
            }, 2000);
          }
        } catch (err) {
          console.error("Failed to copy:", err);
        }
      });

      // Insert button into figure (which has position: relative)
      figure.appendChild(button);
    });
  }, []);

  return null;
}
